/*
  App.QuotesData — a bank of original motivational lines, grouped by theme.
  These are written for this app rather than sourced/attributed to real people,
  so there's no risk of misquoting anyone.
*/
(function () {
  'use strict';
  window.App = window.App || {};

  function make(category, lines) { return lines.map((text) => ({ text, category })); }

  const QUOTES = [
    ...make('Productivity', [
      "Productivity is never an accident. It's a plan and a closed tab.",
      'Done is a decision, not a feeling.',
      'The best system is the one you actually open.',
      'Small tasks cleared make room for big ones to start.',
      'A short list finished beats a long list abandoned.',
      'Momentum is built in five-minute increments.',
      'Your to-do list is a promise to your future self.',
      'Clear the small stuff so the big stuff has room to breathe.',
      'One finished task is worth ten planned ones.',
      'Progress hides inside boring, repeatable steps.',
      'The fastest way through a big project is one item at a time.',
      "You don't need more hours. You need fewer distractions.",
      'Plan the night before, execute in the morning.',
      'A task written down is a task half done.',
      'Batch the small stuff, protect the deep stuff.',
      'Output beats intention, every single time.',
      "The list doesn't need to be perfect. It needs to be started.",
      "Every checkbox is a small vote for who you're becoming.",
    ]),
    ...make('Success', [
      'Success is a few simple disciplines, practiced every day.',
      'Small wins, repeated, become impossible to ignore.',
      'The goal is progress, not perfection.',
      'Success rarely announces itself. It quietly compounds.',
      "You don't rise to your goals, you fall to your systems.",
      'Every expert was once a beginner who kept a list.',
      'Consistency turns ordinary effort into extraordinary results.',
      'The finish line moves for those who keep walking toward it.',
      'Big goals are just small tasks wearing a disguise.',
      "Success is what's left after you show up enough times.",
      'Nobody sees the thousand tries before the one that works.',
      "The people who finish aren't the most talented \u2014 they're the most consistent.",
      'A good plan executed today beats a perfect plan next week.',
      'Your only real competition is who you were yesterday.',
      'Success is boring up close and impressive from far away.',
      "Keep going. Especially when no one's watching.",
      'The reward is usually hiding right after the hardest part.',
      'Ambition without action is just a wish with good branding.',
    ]),
    ...make('Discipline', [
      'Discipline is choosing what you want most over what you want now.',
      'Motivation gets you started. Discipline keeps you going.',
      'Discipline is a muscle. Every small task is a rep.',
      "Do it when you don't feel like it \u2014 that's the whole skill.",
      "The task doesn't care how you feel about it.",
      "Show up on the days you don't want to. That's the job.",
      'Discipline is remembering what you wanted before you got distracted.',
      'Comfort and progress rarely share a room.',
      'The list gets done by people who stop negotiating with themselves.',
      "You won't always feel ready. Start anyway.",
      'Freedom is often just discipline, seen from a distance.',
      'Discipline means finishing the task after the motivation already left.',
      'The five minutes you resisted are usually the ones that mattered most.',
      'A rule you follow beats a goal you merely admire.',
      'Willpower is limited. Systems and habits are not.',
      'Do the boring rep \u2014 the highlight reel is made of them.',
      'Discipline is a quiet promise you keep to no one but yourself.',
      'The task avoided today is twice as heavy tomorrow.',
    ]),
    ...make('Learning', [
      'Every skill was once something you were bad at.',
      'Learning is just failing in a more organized way.',
      'Curiosity is a habit disguised as a personality trait.',
      "The beginner's list is longer, but so is the beginner's growth.",
      "You don't need to feel ready to start learning something new.",
      'Understanding is built one small, uncomfortable question at a time.',
      'Read one more page than you planned to.',
      "Every expert's list once had 'learn the basics' on it.",
      'Growth lives right outside your current routine.',
      'The fastest learners ask the most obvious questions.',
      'Take notes like your future self is going to need them. They will.',
      'A little bit, consistently, beats a lot, occasionally.',
      'Confusion is just the entry fee for understanding.',
      'The best time to learn it was years ago. The next best time is today.',
      'Practice makes permanent \u2014 so practice the right things.',
      'Ask the question that feels too basic to ask.',
      'Knowledge compounds quietly, then all at once.',
      "You're one small lesson away from your next breakthrough.",
    ]),
    ...make('Time management', [
      'You don\u2019t manage time. You manage attention.',
      "Protect your calendar like it's already full \u2014 because it is, with your life.",
      'A full schedule and a productive day are not the same thing.',
      'Time blocks turn intentions into appointments with yourself.',
      'The urgent will always shout louder than the important. Plan accordingly.',
      "Every 'yes' to something is a 'no' to something else.",
      'Ten focused minutes beat sixty distracted ones.',
      'Your calendar shows what you value, not what you say you value.',
      "Plan tomorrow before today ends, while it's still fresh.",
      "Deadlines are just decisions about when 'later' becomes 'now'.",
      "Time isn't the problem. Priorities are.",
      'A five-minute task done now saves a fifty-minute problem later.',
      'The best schedule leaves room for the unexpected.',
      "You can't get time back, but you can spend what's left on purpose.",
      'Single-task the important, batch the trivial.',
      'The calendar remembers what the to-do list forgets.',
      'Guard the first hour of your day \u2014 it sets the tone for the rest.',
      'Busy is not the same as effective.',
    ]),
    ...make('Focus', [
      'Where your attention goes, your results follow.',
      'One tab, one task, one win at a time.',
      'Focus is saying no to nineteen good ideas to say yes to one.',
      "Deep work happens in the space distraction can't reach.",
      'Multitasking is just doing several things badly, at once.',
      'The task in front of you deserves the whole of your attention.',
      'Close the extra tabs. Close the extra thoughts.',
      'A quiet mind gets more done than a busy one.',
      "Attention is the one currency you can't earn back.",
      'Focus turns a long list into a short afternoon.',
      'Give the next twenty-five minutes everything, then rest completely.',
      'Distraction feels productive. Focus actually is.',
      "The phone can wait. The task in front of you can't wait forever.",
      'Single-tasking is a superpower disguised as a limitation.',
      'Silence the noise, and the next step gets obvious.',
      'Your focus is a spotlight \u2014 point it at one thing at a time.',
      'The work expands to fill the attention you give it.',
      'Interruptions are loud. Progress is quiet. Feed the quiet one.',
    ]),
    ...make('Consistency', [
      "Consistency turns 'someday' into 'done'.",
      'Show up small, every day, and watch it become big.',
      "A streak is just a series of days you didn't quit.",
      'Consistency beats intensity, nearly every time.',
      'The habit matters more than the mood you have about it.',
      'Keep the chain unbroken \u2014 even a tiny link holds.',
      'What you repeat, you become.',
      'One percent better, repeated, is how everything actually changes.',
      "Discipline fades. Systems and routines don't ask permission.",
      'Skipping once is a day off. Skipping twice is a new habit.',
      'The boring middle is where the real progress happens.',
      'Consistency is the bridge between goals and results.',
      "You don't need a perfect day. You need another day.",
      'Small, repeated actions outperform occasional heroics.',
      "The streak isn't the point \u2014 what it builds is.",
      "Every day you show up is a vote for who you're becoming.",
      'A habit kept on a bad day is worth more than one kept on a good one.',
      'Long-term consistency beats short-term intensity, every time.',
    ]),
  ];

  QUOTES.forEach((q, i) => { q.id = 'q' + i; });

  App.QuotesData = QUOTES;
})();
